### ISSUE TITLE
SetMethod throwing exception after upgrading to v8.0.0

### ISSUE THREAD

**Issue by gamelaster** [nodejs/help#644]
* **Node.js Version**: v8.0.0
* **OS**: Windows 10 x64
* **Scope (install, code, runtime, meta, other?)**: Runtime (native/embedding)
* **Module (and version) (if relevant)**:

I embedded successfully NodeJS v7.10.0 into my C++ project. After updating to v8.0.0, I getting `Access violation reading location` on first line of stacktrace.  
Stacktrace:
```
	node.dll!v8::FunctionTemplate::SetCallHandler(void(*)(const v8::FunctionCallbackInfo<v8::Value> &) callback, v8::Local<v8::Value> data) Line 1393	C++
 	node.dll!v8::FunctionTemplateNew(v8::internal::Isolate * isolate, void(*)(const v8::FunctionCallbackInfo<v8::Value> &) callback, v8::Local<v8::Value> data, v8::Local<v8::Signature> signature, int length, bool do_not_cache, v8::Local<v8::Private> cached_property_name) Line 1309	C++
 	node.dll!v8::FunctionTemplate::New(v8::Isolate * isolate, void(*)(const v8::FunctionCallbackInfo<v8::Value> &) callback, v8::Local<v8::Value> data, v8::Local<v8::Signature> signature, int length, v8::ConstructorBehavior behavior) Line 1332	C++
 	nodejs-module.dll!node::gameModule::Initialize(v8::Local<v8::Object> target, v8::Local<v8::Value> unused, v8::Local<v8::Context> context) Line 176	C++
 	node.dll!node::Binding(const v8::FunctionCallbackInfo<v8::Value> & args) Line 2744	C++
 	node.dll!v8::internal::FunctionCallbackArguments::Call(void(*)(const v8::FunctionCallbackInfo<v8::Value> &) f) Line 26	C++
 	node.dll!v8::internal::`anonymous namespace'::HandleApiCallHelper<0>(v8::internal::Isolate * isolate, v8::internal::Handle<v8::internal::HeapObject> function, v8::internal::Handle<v8::internal::HeapObject> new_target, v8::internal::Handle<v8::internal::FunctionTemplateInfo> fun_data, v8::internal::Handle<v8::internal::Object> receiver, v8::internal::BuiltinArguments args) Line 113	C++
 	node.dll!v8::internal::Builtin_Impl_HandleApiCall(v8::internal::BuiltinArguments args, v8::internal::Isolate * isolate) Line 140	C++
 	node.dll!v8::internal::Builtin_HandleApiCall(int args_length, v8::internal::Object * * args_object, v8::internal::Isolate * isolate) Line 128	C++
```
Code:
```c++
		void Initialize(v8::Local<v8::Object> target, v8::Local<v8::Value> unused, v8::Local<v8::Context> context)
		{
			Environment* env = Environment::GetCurrent(context);

			env->SetMethod(target, "onResourceLoad", OnResourceLoadFunction); //Line 176 of nodejs-module
			env->SetMethod(target, "onEvent", OnEventFunction);
...
NODE_MODULE_CONTEXT_AWARE_BUILTIN(gameModule, node::gameModule::Initialize);
```
JS:
```js
global.gameModule = process.binding('gameModule');
```

**Comment by bnoordhuis** [comment]
Have you tried a rebuild from scratch.  My hunch would be that some of your object files are still compiled for the older node version.

**Comment by gamelaster** [comment]
I tried `Rebuild` in VS, not helped 😞

**Comment by bnoordhuis** [comment]
Okay, what happens when you run it under a debugger?

**Comment by gamelaster** [comment]
I didn't have Debugger implemented yet. I have just Visual Studio Debugger available.
![image](https://cloud.githubusercontent.com/assets/1665373/26639045/0fb0edf4-4624-11e7-815c-e3d832ed2091.png)

**Comment by bnoordhuis** [comment]
It looks like a failed JS heap allocation inside V8 but as to why it fails, your guess is as good as mine.

**Comment by gamelaster** [comment]
I checked the differences on setup of NodeJS (environment etc.), one of them is adding the `Environment::AsyncHooks::ExecScope` before loading environment, but after adding that I can't compile because unresolved external symbols (`node::Assert`, I tried to solve it before (I can't use NodeJS's V8 Array Buffer Allocator for this)).
I just don't know where to search, everything works perfectly on v7.10.0 🤔

**Comment by gamelaster** [comment]
bump, tested on v8.10.0, same behavior :-/

**Comment by bnoordhuis** [comment]
I see you emailed me your code but I don't have time to look into it (and neither do I use Windows.)  You'll have to figure this out yourself.

**Comment by refack** [comment]
@nodejs/async_hooks

**Comment by refack** [comment]
@gamelaster can you send me your code?

**Comment by gamelaster** [comment]
@refack I sent email to mail in NodeJS readme.

**Comment by refack** [comment]
looks like https://github.com/nodejs/node/commit/c0bde73f1bbfedd4e77ddf87cf0bcec7bac9a61e broke embedding (at least on windows)

**Comment by AndreasMadsen** [comment]
@refack the addon tests runs on windows CI, correct?

**Comment by refack** [comment]
Yes. https://github.com/nodejs/node/blob/master/vcbuild.bat#L48

**Comment by trevnorris** [comment]
@refack Have an idea why this passes in Windows CI, or how we might replicate this in an addon test?

**Comment by gamelaster** [comment]
@refack @AndreasMadsen 
AndreasMadsen/node@48ef6a20e04a34f6ebc43bcb892b319a300a47de doesn't fixed this issue.

**Comment by gireeshpunathil** [comment]
@gamelaster - is this still an issue for you? that is, with the latest version of node? please let me know.

**Comment by gireeshpunathil** [comment]
closing due to inactivity, please re-open if it is still outstanding.
