### ISSUE TITLE
Cannot find module 'crypto'

### ISSUE THREAD

**Issue by thatham** [nodejs/help#1322]
Hi,
I'm getting the below error 
ERROR in ./node_modules/jwa/index.js
Module not found: Error: Can't resolve 'crypto' in '~\node_modules\jwa'.
after upgrade from Angular version 5 to 6.

In ./node_modules/jwa/index.js crypto has been declared as below
`const crypto = require('crypto');`

when I try node > crypto is working on node console, but got error while building using `ng build`

this is my env:

"dependencies": {
    "angular/animations": "6.0.0",
    "angular/common": "6.0.0",
    "angular/compiler": "6.0.0",
    "angular/core": "6.0.0",
    "angular/forms": "6.0.0",
    "angular/http": "6.0.0",
    "angular/platform-browser": "6.0.0",
    "angular/platform-browser-dynamic": "6.0.0",
    "angular/platform-server": "6.0.0",
    "angular/router": "6.0.0",
    "bcryptjs": "^2.4.3",
    "body-parser": "^1.18.3",
    "buffer": "^5.1.0",
    "dotenv": "^5.0.1",
    "ejs": "2.5.9",
    "events": "^3.0.0",
    "express": "4.16.3",
    "fs": "0.0.1-security",
    "http-status-codes": "^1.3.0",
    "jsonwebtoken": "^8.2.1",
    "nodemailer": "4.6.4",
    "pg": "7.4.2",
    "randomstring": "^1.1.5",
    "rxjs": "6.1.0",
    "sequelize": "4.37.6",
    "stream": "0.0.2",
    "timers": "^0.1.1",
    "zone.js": "0.8.26"
  },
  "devDependencies": {
    "angular-devkit/build-angular": "^0.6.3",
    "angular/cli": "^6.0.3",
    "angular/compiler-cli": "^6.0.3",
    "types/bcryptjs": "^2.4.1",
    "types/body-parser": "1.17.0",
    "types/dotenv": "4.0.3",
    "types/express": "^4.0.39",
    "types/jsonwebtoken": "7.2.7",
    "types/node": "10.0.4",
    "types/sequelize": "4.27.17",
    "codelyzer": "4.3.0",
    "concurrently": "^3.5.1",
    "tslint": "5.10.0",
    "typescript": "^2.7.2"
  }

Please help

**Comment by KlausVonnemann** [comment]
me be this wokrs:   Change crypto to crypto-js
                               var crypto = require('crypto-js');


![image](https://user-images.githubusercontent.com/36073676/41315653-6f530b9e-6e90-11e8-878c-7d20027a119b.png)

**Comment by naltun** [comment]
@thatham does the suggestion from @KlausVonnemann works?

**Comment by thatham** [comment]
@naltun Crypto is a built in nodejs. So there's no need to replace with crypto-js. But I've found a workaround, the error is from the @angular-devkit which is in node_modules.

I've modified the below file
node_modules//src/angular-cli-files/models/webpack-configs/browser.js

at the bottom of the page:
node: false

Change to:
node: { crypto: true, stream: true, buffer: true }

this might be a dirty fix, but really solved the problem

Thank you all

**Comment by gireeshpunathil** [comment]
closing then, cheers

**Comment by RihardsVeters** [comment]
now node.js server isn't running.

**Comment by fjoalland** [comment]
> node: { crypto: true, stream: true, buffer: true }

Nice solution, but a little ugly. Did you find a better one ?
