### ISSUE TITLE
AsyncWrite is not a function

### ISSUE THREAD

**Issue by copa017** [nodejs/help#1507]
* **10.10.0**:
* **Win10**:
* **install**:
* **npm**:

I have the output "AsyncWrite is not a function" problem, no matter what I am going to install on my Windows 10.
I freshly installed Node 8.12.0 and 10.10.0 - no difference.

I tried: rebooting, force clean cache , run as admin, delete npm&node folders in appdata... to no avail

Thank you in advance!

npm install electron
npm ERR! asyncWrite is not a function
npm ERR! pna.nextTick is not a function

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   'electron' ]
2 info using npm@6.4.1
3 info using node@v10.10.0
4 verbose config Skipping project config: C:\Users\user/.npmrc. (matches userconfig)
5 verbose npm-session b18e6ffbb1dcad91
6 silly install loadCurrentTree
7 silly install readLocalPackageData
8 verbose stack TypeError: asyncWrite is not a function
8 verbose stack     at onwrite (C:\Program Files\nodejs\node_modules\npm\node_modules\readable-stream\lib\_stream_writable.js:480:7)
8 verbose stack     at WritableState.onwrite (C:\Program Files\nodejs\node_modules\npm\node_modules\readable-stream\lib\_stream_writable.js:180:5)
8 verbose stack     at WriteStream.to [as _worker] (C:\Program Files\nodejs\node_modules\npm\node_modules\pacote\node_modules\make-fetch-happen\cache.js:154:13)
8 verbose stack     at WriteStream._write (C:\Program Files\nodejs\node_modules\npm\node_modules\mississippi\node_modules\flush-write-stream\index.js:35:13)
8 verbose stack     at doWrite (C:\Program Files\nodejs\node_modules\npm\node_modules\readable-stream\lib\_stream_writable.js:428:64)
8 verbose stack     at writeOrBuffer (C:\Program Files\nodejs\node_modules\npm\node_modules\readable-stream\lib\_stream_writable.js:417:5)
8 verbose stack     at WriteStream.Writable.write (C:\Program Files\nodejs\node_modules\npm\node_modules\readable-stream\lib\_stream_writable.js:334:11)
8 verbose stack     at WriteStream.to [as _worker] (C:\Program Files\nodejs\node_modules\npm\node_modules\pacote\node_modules\make-fetch-happen\cache.js:171:25)
8 verbose stack     at WriteStream._write (C:\Program Files\nodejs\node_modules\npm\node_modules\mississippi\node_modules\flush-write-stream\index.js:35:13)
8 verbose stack     at doWrite (C:\Program Files\nodejs\node_modules\npm\node_modules\readable-stream\lib\_stream_writable.js:428:64)
8 verbose stack     at writeOrBuffer (C:\Program Files\nodejs\node_modules\npm\node_modules\readable-stream\lib\_stream_writable.js:417:5)
8 verbose stack     at WriteStream.Writable.write (C:\Program Files\nodejs\node_modules\npm\node_modules\readable-stream\lib\_stream_writable.js:334:11)
8 verbose stack     at WriteStream.to [as _worker] (C:\Program Files\nodejs\node_modules\npm\node_modules\pacote\node_modules\make-fetch-happen\cache.js:182:19)
8 verbose stack     at WriteStream._write (C:\Program Files\nodejs\node_modules\npm\node_modules\mississippi\node_modules\flush-write-stream\index.js:35:13)
8 verbose stack     at doWrite (C:\Program Files\nodejs\node_modules\npm\node_modules\readable-stream\lib\_stream_writable.js:428:64)
8 verbose stack     at writeOrBuffer (C:\Program Files\nodejs\node_modules\npm\node_modules\readable-stream\lib\_stream_writable.js:417:5)
9 verbose cwd C:\Users\user
10 verbose Windows_NT 10.0.17134
11 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "electron"
12 verbose node v10.10.0
13 verbose npm  v6.4.1
14 error asyncWrite is not a function
15 verbose exit [ 1, true ]

**Comment by copa017** [comment]
And I am also getting

```
C:\Users\username>npm cache verify
npm ERR! pna.nextTick is not a function
Unhandled rejection TypeError: pna.nextTick is not a function
    at emitReadable (C:\Program Files\nodejs\node_modules\npm\node_modules\readable-stream\lib\_stream_readable.js:498:25)
```

**Comment by francisco-rg** [comment]
The same with Windows 10, NPM 6.4.1 and Node 10.11.0

**Comment by cbourdage** [comment]
I've been having the same issue as well attempting to update to 8.12 from 8.11.4 using `n`. I can't figure out if this is related to `n` or 8.12.0. Downgrading to 8.11.4 `npm install` works no problems but upgrading to 8.12.0 produces the same messages as described above. Same thing with the `npm cache verify`. 

macOS: 10.13.2
node: 8.12.0
npm: 6.4.1

@copa017 were you using `n` package manager and were you able to solve the above?

**Comment by copa017** [comment]
@cbourdage no, I don't have n (I think there is no n on windows).
I wasn't able to solve this.
But by totally uninstalling everything related to node, npm,.. and using then Scoop to install Electron I could do my work.

**Comment by specoff** [comment]
**It worked for me (win 10):**
1. Uninstall node. 
2. Run new install Node to NOT System disk. For me is: 
`I:\Node\`

**Comment by addaleax** [comment]
This *sounds* like there’s still some leftover files from an old `npm` installation that get in the way.

I know this is a lot to ask, but could somebody try to come up with a reproduction for this issue?

**Comment by PacoDu** [comment]
Same here, for me the project is working with `node v11.4.0` and `npm 6.4.1` on my computer, but gitlab-ci fails to run `npm install` with docker image `node:11`, `node:11-alpine`, `node:10`.
Same error after clearing the runner cache.

**Comment by RayBowman2017b** [comment]
I'm getting the same thing.

npm ERR! asyncWrite is not a function
npm ERR! pna.nextTick is not a function

This happens whenever I try to install anything.

Windows 10 Pro 1809 64-bit

2 info using npm@6.4.1
3 info using node@v10.15.3

$ npm --versions

{ ‘typescript-complete-course’: ‘1.0.0’,
npm: ‘6.4.1’,
ares: ‘1.15.0’,
cldr: ‘33.1’,
http_parser: ‘2.8.0’,
icu: ‘62.1’,
modules: ‘64’,
napi: ‘3’,
nghttp2: ‘1.34.0’,
node: ‘10.15.3’,
openssl: ‘1.1.0j’,
tz: ‘2018e’,
unicode: ‘11.0’,
uv: ‘1.23.2’,
v8: ‘6.8.275.32-node.51’,
zlib: ‘1.2.11’ }

$ node -p process.platform

win32

I’ve used the package installer for node 10.15.3 to uninstall NodeJs,
then reboot Windows 10,
then reinstall node

It did not work.

Is there a removal tool that will uninstall NodeJs correctly?

**Comment by RayBowman2017b** [comment]
There are certain folders that can be left after an uninstall. See this blogport:

https://kalliphant.com/nodejs-npm-windows-install/

Uninstall node.js and npm installed using Windows Installer (msi)
To uninstall node.js and npm, Open Windows "Control Panel" -> "Uninstall a program", select Node.js and click on uninstall to uninstaill both node.js and npm

Cleanup directories
After the uninstall, look for the following folders and delete them if exists
* Nodejs installed directory
* npm and npm-cache directories from %appdata% directory
* npmrc directory from user home directory ( C:\Users\{User} )

After using Windows uninstall to remove NodeJS, make sure that the folders mentioned in the blogpost have been deleted, reboot, then reinstall NodeJS.

Worked for me.

HTH.

**Comment by gireeshpunathil** [comment]
ping @copa017

**Comment by copa017** [comment]
Sorry, I cannot reproduce this (old) behavior anymore.
Installed 12.04 today and it works as expected.
Thanks to everyone!

Maybe results from @francisco-rg @specoff  @PacoDu  or @cbourdage ?

**Comment by lanlonggang** [comment]
mark,I'm on the same trouble. node: v10.15.3  npm: 6.4.1  pc: win10

**Comment by gireeshpunathil** [comment]
no response, closing. pls re-open if there is anything outstanding here
