### ISSUE TITLE
Fail To Build in x86 MacOS 12.3(Monterey)

### ISSUE THREAD

**Issue by Leaking** [nodejs/help#3822]
### Version

14.17.2)

### Platform

Darwin QUINNHZCHEN-MB0 21.4.0 Darwin Kernel Version 21.4.0: Mon Feb 21 20:34:37 PST 2022; root:xnu-8020.101.4~2/RELEASE_X86_64 x86_64

### What steps will reproduce the bug?

my macos sdk is MacOSX12.3.sdk
my xcode version is 13.3

1、clone node repo，and checkout 14.17.2
2、run ./configure
3、run make -4j

and then i come with this error 
```
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/__errc:190:43: error: use of undeclared identifier 'EOWNERDEAD'
    owner_dead                          = EOWNERDEAD,
                                          ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/__errc:198:43: error: use of undeclared identifier 'ENOTRECOVERABLE'
    state_not_recoverable               = ENOTRECOVERABLE,

```

### What do you see instead?

```
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/__errc:190:43: error: use of undeclared identifier 'EOWNERDEAD'
    owner_dead                          = EOWNERDEAD,
                                          ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/__errc:198:43: error: use of undeclared identifier 'ENOTRECOVERABLE'
    state_not_recoverable               = ENOTRECOVERABLE,
```

**Comment by Leaking** [comment]
> Could you please share the complete error logs? It must have things like
> 
> ```
> In file included from <file>:<line>:<column>,
> from <file>:<line>,
> from <file>:<line>:
> /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/__errc:190:43: error: use of undeclared identifier 'EOWNERDEAD'
>     owner_dead                          = EOWNERDEAD,
>                                           ^
> /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/__errc:198:43: error: use of undeclared identifier 'ENOTRECOVERABLE'
>     state_not_recoverable               = ENOTRECOVERABLE,
> ```
> 
> before the error you shared, right?

<img width="1092" alt="image" src="https://user-images.githubusercontent.com/6383426/163001529-f311b7e1-0f80-4ab4-8e74-1352b619b212.png">

**Comment by RaisinTen** [comment]
Including `condition_variable` does compile for me. Are you getting this error even after fully launching the Xcode app downloaded from the App Store?

**Comment by Leaking** [comment]
> I tried to compile a standalone program that includes this header file and it compiles okay with the 12.3 SDK. I'm suspecting that you would need to fully launch the Xcode app first (preferably downloaded from the App Store), otherwise you'll keep hitting such issues (this week I came across another Xcode SDK issue and that was the suggestion in [this](https://groups.google.com/a/chromium.org/g/chromium-dev/c/zLdnnbadgZE) thread). In any case, I don't think this is a bug in Node.js, so I'm moving this to the help repo.

i have uninstall xcode and download it again from app store, but the same error occurs.
i come across the above error in my macbook.
it's weird, i can build node in may imac, it also have the sdk 12.3 .

**Comment by RaisinTen** [comment]
Does `/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/errno.h` exist for you? I think that has the definition for `EOWNERDEAD`.

**Comment by RaisinTen** [comment]
> i have uninstall xcode and download it again from app store

Did you try to launch the Xcode app and answer all its prompts? _I think_ it's supposed to download few additional things then.

**Comment by Leaking** [comment]
> > i have uninstall xcode and download it again from app store
> 
> Did you try to launch the Xcode app and answer all its prompts? _I think_ it's supposed to download few additional things then.

i have approve all prompts

**Comment by RaisinTen** [comment]
Does this standalone program compile?
```cc
#include <condition_variable>

int main() {
  EOWNERDEAD;
  return 0;
}
```

**Comment by Leaking** [comment]
> EOWNERDEAD

yes

**Comment by RaisinTen** [comment]
Hmm, I didn't expect that. There's clearly some missing information here because I'm not able to reproduce this on my system which also has the same setup as you described in this issue.

Might be worth trying out Ben's solution too:

> On the other hand, it's probably possible to work around it by building node with `-D_POSIX_C_SOURCE=200809`; the defines in errno.h are guarded on it.

because it was used to fix a similar issue (https://github.com/arbor-sim/arbor/issues/562#issuecomment-409970434) for GCC on macOS in https://github.com/unicode-org/icu/pull/1052:
```h
#if !defined _POSIX_C_SOURCE && \
    defined(__APPLE__) && defined(__MACH__) && !defined(__clang__)
// Needed to prevent EOWNERDEAD issues with GCC on Mac
#define _POSIX_C_SOURCE 200809L
#endif
```
(taken from https://github.com/nodejs/node/blob/24adba675179ebba363d46f5dd30685d58cdb7f4/deps/icu-small/source/common/uposixdefs.h#L71-L75)
