### ISSUE TITLE
Native add-on compilation error in NODE_MODULE function on 12.0.0, works on 11.15.0

### ISSUE THREAD

**Issue by jhecking** [nodejs/help#1911]
* **Node.js Version**: v12.0.0
* **OS**: macOS/Ubuntu 14.04
* **Scope (install, code, runtime, meta, other?)**: compile time
* **Module (and version) (if relevant)**:

I'm maintaining the [`aerospike`](https://www.npmjs.com/package/aerospike) package, a client SDK for the Aerospike No-SQL database. On Node.js versions up to and including v11.15.0 this package compiles and works fine. But starting with v12.0.0 I'm getting a compile time error when building the native add-on, that I haven't been able to resolve.

The error occurs in this function (slightly abbreviated):

```c++
void Aerospike(Handle<Object> exports, Handle<Object> module)
{
	AerospikeClient::Init();
	export("client", Nan::New<FunctionTemplate>(client)->GetFunction());
        // more exports
}

NODE_MODULE(aerospike, Aerospike)
```

And the error I'm getting is:

```
  CXX(target) Release/obj.target/aerospike/src/main/aerospike.o
../src/main/aerospike.cc:102:6: error: variable has incomplete type 'void'
void Aerospike(Handle<Object> exports, Handle<Object> module)
     ^
../src/main/aerospike.cc:102:23: error: 'Object' does not refer to a value
void Aerospike(Handle<Object> exports, Handle<Object> module)
                      ^
/Users/jhecking/.node-gyp/12.0.0/include/node/v8.h:3356:17: note: declared here
class V8_EXPORT Object : public Value {
                ^
../src/main/aerospike.cc:102:16: error: use of undeclared identifier 'Handle'
void Aerospike(Handle<Object> exports, Handle<Object> module)
               ^
../src/main/aerospike.cc:102:31: error: use of undeclared identifier 'exports'
void Aerospike(Handle<Object> exports, Handle<Object> module)
                              ^
../src/main/aerospike.cc:102:47: error: 'Object' does not refer to a value
void Aerospike(Handle<Object> exports, Handle<Object> module)
                                              ^
/Users/jhecking/.node-gyp/12.0.0/include/node/v8.h:3356:17: note: declared here
class V8_EXPORT Object : public Value {
                ^
../src/main/aerospike.cc:102:40: error: use of undeclared identifier 'Handle'
void Aerospike(Handle<Object> exports, Handle<Object> module)
                                       ^
../src/main/aerospike.cc:102:55: error: use of undeclared identifier 'module'
void Aerospike(Handle<Object> exports, Handle<Object> module)
                                                      ^
../src/main/aerospike.cc:102:62: error: expected ';' after top level declarator
void Aerospike(Handle<Object> exports, Handle<Object> module)
                                                             ^
                                                             ;
8 errors generated.
```

The module uses the older C++ add-on API, not n-api. I'm using the latest version nan v2.13.2.

The error can also be seen in this Travis CI job: https://travis-ci.org/aerospike/aerospike-client-nodejs/jobs/523788617.
The full source code is here: https://github.com/aerospike/aerospike-client-nodejs/blob/2b9554d1158abda58c17cfbd0438d78f0212ef9e/src/main/aerospike.cc#L102

**Comment by bnoordhuis** [comment]
Replace `Handle<Object>` with `Local<Object>`. V8 removed the `Handle<T>` class.

Replace `export()` with `Nan::Set()` and/or `Nan::SetMethod()`.

**Comment by jhecking** [comment]
Thanks for your help! I had [found the issue](https://github.com/aerospike/aerospike-client-nodejs/commit/a7975f55f8ff8470ee574a2fb8fcf7325e83300d#diff-cbd0961107a2bea0e391fc2c164963ca) eventually myself and fixed it by using the `NAN_MODULE_INIT` macro.
