### ISSUE TITLE
module not found readable-stream/Transform

### ISSUE THREAD

**Issue by abenson229** [nodejs/help#1809]
* **Node.js Version**:  11.10.1
* **OS**: Windows 10 64 bit
* **Scope (install, code, runtime, meta, other?)**:  Installing NPM package
* **Module (and version) (if relevant)**:  Any NPM module

Attempting to install any NPM package results in an error MODULE NOT FOUND readable-stream/Transform

I've deleted the node-modules folder, reinstalled v11.10.1 and still cannot install anything.  I've since gone back to v10.15.2 and have no issues with that version.

**Comment by yathamravali** [comment]
@abenson229
Can u post the debug log?

**Comment by kcaporaso** [comment]
Getting the same thing on macOS (High Sierra) with node and npm installed via macports, debug log below.  I can't even install readable-stream/transform because I get this error, it's like a weird circular reference.

```
npm ERR! code MODULE_NOT_FOUND
npm ERR! Cannot find module 'readable-stream/transform'
```

```
0 info it worked if it ends with ok
1 verbose cli [ '/opt/local/bin/node',
1 verbose cli   '/opt/local/bin/npm',
1 verbose cli   'install',
1 verbose cli   'readable-stream/transform' ]
2 info using npm@6.9.0
3 info using node@v10.15.3
4 verbose stack Error: Cannot find module 'readable-stream/transform'
4 verbose stack     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:582:15)
4 verbose stack     at Function.Module._load (internal/modules/cjs/loader.js:508:25)
4 verbose stack     at Module.require (internal/modules/cjs/loader.js:637:17)
4 verbose stack     at require (internal/modules/cjs/helpers.js:22:18)
4 verbose stack     at Object.<anonymous> (/opt/local/lib/node_modules/npm/node_modules/cacache/node_modules/mississippi/node_modules/through2/through2.js:1:79)
4 verbose stack     at Module._compile (internal/modules/cjs/loader.js:701:30)
4 verbose stack     at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
4 verbose stack     at Module.load (internal/modules/cjs/loader.js:600:32)
4 verbose stack     at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
4 verbose stack     at Function.Module._load (internal/modules/cjs/loader.js:531:3)
4 verbose stack     at Module.require (internal/modules/cjs/loader.js:637:17)
4 verbose stack     at require (internal/modules/cjs/helpers.js:22:18)
4 verbose stack     at Object.<anonymous> (/opt/local/lib/node_modules/npm/node_modules/cacache/node_modules/mississippi/index.js:5:26)
4 verbose stack     at Module._compile (internal/modules/cjs/loader.js:701:30)
4 verbose stack     at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
4 verbose stack     at Module.load (internal/modules/cjs/loader.js:600:32)
5 verbose cwd /private/var/www/www.vspdirect.com
6 verbose Darwin 17.7.0
7 verbose argv "/opt/local/bin/node" "/opt/local/bin/npm" "install" "readable-stream/transform"
8 verbose node v10.15.3
9 verbose npm  v6.9.0
10 error code MODULE_NOT_FOUND
11 error Cannot find module 'readable-stream/transform'
12 verbose exit [ 1, true ]
```

**Comment by kcaporaso** [comment]
Found my issue, had to completely uninstall npm6 and then delete the /opt/local/lib/node_modules/npm dir and then reinstall npm6.

**Comment by gireeshpunathil** [comment]
ping @abenson229

**Comment by escarls** [comment]
I had the exact same issue after upgrading node.js to 10.16.0 LTS from 9.5 on Windows.
It's because you had an old version of the mississippi in /opt/local/lib/node_modules/npm/node_modules/cacache/node_modules/mississippi
Just delete that directory and you're good to go.
For those that experiences this on Windows, the path to the old module is:
C:\Program Files\nodejs\node_modules\npm\node_modules\cacache\node_modules

**Comment by MaMrEzO** [comment]
Hey guys,
At first I have no **/opt/local/lib/node_modules** to remove, Even I **removed**(unInstall) both of **node** and **npm** and reinstalled them many times with no _success_!
`ls: cannot access '/opt/local/lib/node_modules/': No such file or directory
`
So, Is there anyone to tell me where is the npm looking for this module?

I just git cloned a sample of angularjs and entered the folder and hit the famous "npm install"!

**Comment by vamsykreddy** [comment]
I also am facing the same issue on Windows machine for node 11.11.0. npm install was working fine for me on node 8 on the same machine but when upgraded to 11 it has thrown `npm ERR! asyncwrite is not a function`. As suggested in the internet, I uninstalled node and delete folders related to node and npm from program files and AppData and did a fresh installation and now I am facing this `npm ERR! Cannot find module 'readable-stream/transform'`.

```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install' ]
2 info using npm@6.7.0
3 info using node@v11.11.0
4 verbose stack Error: Cannot find module 'readable-stream/transform'
4 verbose stack     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:649:15)
4 verbose stack     at Function.Module._load (internal/modules/cjs/loader.js:575:25)
4 verbose stack     at Module.require (internal/modules/cjs/loader.js:705:19)
4 verbose stack     at require (internal/modules/cjs/helpers.js:14:16)
4 verbose stack     at Object.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\mississippi\node_modules\through2\through2.js:1:17)
4 verbose stack     at Module._compile (internal/modules/cjs/loader.js:799:30)
4 verbose stack     at Object.Module._extensions..js (internal/modules/cjs/loader.js:810:10)
4 verbose stack     at Module.load (internal/modules/cjs/loader.js:666:32)
4 verbose stack     at tryModuleLoad (internal/modules/cjs/loader.js:606:12)
4 verbose stack     at Function.Module._load (internal/modules/cjs/loader.js:598:3)
4 verbose stack     at Module.require (internal/modules/cjs/loader.js:705:19)
4 verbose stack     at require (internal/modules/cjs/helpers.js:14:16)
4 verbose stack     at Object.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\mississippi\index.js:5:26)
4 verbose stack     at Module._compile (internal/modules/cjs/loader.js:799:30)
4 verbose stack     at Object.Module._extensions..js (internal/modules/cjs/loader.js:810:10)
4 verbose stack     at Module.load (internal/modules/cjs/loader.js:666:32)
5 verbose cwd D:\Users\private\Desktop\www
6 verbose Windows_NT 6.3.9600
7 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
8 verbose node v11.11.0
9 verbose npm  v6.7.0
10 error code MODULE_NOT_FOUND
11 error Cannot find module 'readable-stream/transform'
12 verbose exit [ 1, true ]

```

**Comment by PandaWhoCodes** [comment]
I fixed it by uninstalling and deleting nodejs folder and reinstalling.
Got this error after updating to 10

**Comment by himadriganguly** [comment]
Is the issue solved now?

**Comment by gireeshpunathil** [comment]
closing as inactive, pls reopen if this is outstanding, and when you can provide details.

**Comment by AnnEmily** [comment]
None of the solutions above worked for me. Maybe not totally kasher as a workaround, but everything went fine after I replaced in webpack.config.js:

`_stream_transform: require.resolve('readable-stream/transform'),`

with

`_stream_transform: require.resolve('readable-stream/lib/_stream_transform'),`
