### ISSUE TITLE
node-gyp compilation fails on static_assert with node v14.5.0

### ISSUE THREAD

**Issue by scimarin** [nodejs/help#2826]
* **Version**: 14.5.0
* **Platform**: Linux workstation 5.7.7-arch1-1 SMP PREEMPT Wed, 01 Jul 2020 14:53:16 +0000 x86_64 GNU/Linux

### What steps will reproduce the bug?
- Update nodejs to 14.5.0 on your system (was at 14.4.0 before that).
- try to install isolated-vm with: `npm i isolated-vm` . This worked with 14.4.0.
- now greeted with the following error:

`node-aead-crypto@2.2.0 preinstall /home/sergiu/Code/withthegrid/platform/node_modules/node-aead-crypto
node lib/preinstall.js`

`node-aead-crypto not needed on this system, since all ciphers are natively supported`

`isolated-vm@3.3.3 install /home/sergiu/Code/withthegrid/platform/node_modules/isolated-vm`
`node-gyp rebuild --release -j 4`

`make: Entering directory '/home/sergiu/Code/withthegrid/platform/node_modules/isolated-vm/build'`
`  CXX(target) Release/obj.target/nortti/src/external_copy/serializer_nortti.o`
`  CXX(target) Release/obj.target/nortti/src/isolate/allocator.o`
`In file included from ../src/external_copy/external_copy.h:2,`
`                 from ../src/external_copy/serializer.h:2,`
`                 from ../src/external_copy/serializer_nortti.cc:1:`
`/home/sergiu/.cache/node-gyp/14.5.0/include/node/v8.h: In instantiation of ‘void v8::ReturnValue<T>::Set(bool) [with T = void]’:
../src/isolate/generic/callbacks.h:91:32:   required from here`
`/home/sergiu/.cache/node-gyp/14.5.0/include/node/v8.h:11106:46: error: static assertion failed: type check
11106 |   static_assert(std::is_base_of<T, Boolean>::value, "type check");
      |                                              ^~~~~`
`/home/sergiu/.cache/node-gyp/14.5.0/include/node/v8.h: In instantiation of ‘void v8::PersistentBase<T>::SetWeak(P*, typename v8::WeakCallbackInfo<P>::Callback, v8::WeakCallbackType) [with P = ivm::ClassHandle; T = v8::Object; typename v8::WeakCallbackInfo<P>::Callback = void (*)(const v8::WeakCallbackInfo<ivm::ClassHandle>&)]’:
../src/isolate/class_handle.h:109:18:   required from ‘void ivm::ClassHandle::SetWeak(P*) [with P = ivm::ClassHandle; void (* F)(P*) = ivm::ClassHandle::WeakCallback]’`
`../src/isolate/class_handle.h:132:55:   required from here`
`/home/sergiu/.cache/node-gyp/14.5.0/include/node/v8.h:10830:16: warning: cast between incompatible function types from ‘v8::WeakCallbackInfo<ivm::ClassHandle>::Callback’ {aka ‘void (*)(const v8::WeakCallbackInfo<ivm::ClassHandle>&)’} to ‘Callback’ {aka ‘void (*)(const v8::WeakCallbackInfo<void>&)’} [-Wcast-function-type]
10830 |                reinterpret_cast<Callback>(callback), type);
      |                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~`
`make: *** [nortti.target.mk:155: Release/obj.target/nortti/src/external_copy/serializer_nortti.o] Error 1`
`make: *** Waiting for unfinished jobs....`
`make: Leaving directory '/home/sergiu/Code/withthegrid/platform/node_modules/isolated-vm/build'`
`gyp ERR! build error`
`gyp ERR! stack Error: `make` failed with exit code: 2`
`gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/node-gyp/lib/build.js:194:23)`
`gyp ERR! stack     at ChildProcess.emit (events.js:314:20)`
`gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:276:12)`
`gyp ERR! System Linux 5.7.7-arch1-1`
`gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--release" "-j" "4"`
`gyp ERR! cwd /home/sergiu/Code/withthegrid/platform/node_modules/isolated-vm`
`gyp ERR! node -v v14.5.0`
`gyp ERR! node-gyp -v v6.1.0`
`gyp ERR! not ok`
`npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.3 (node_modules/fsevents):`
`npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})`
`npm WARN optional SKIPPING OPTIONAL DEPENDENCY: node-aead-crypto@2.2.0 (node_modules/node-aead-crypto):`
`npm WARN optional SKIPPING OPTIONAL DEPENDENCY: node-aead-crypto@2.2.0 preinstall: node lib/preinstall.js`
`npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1`

`npm ERR! code ELIFECYCLE`
`npm ERR! errno 1`
`npm ERR! isolated-vm@3.3.3 install: node-gyp rebuild --release -j 4`
`npm ERR! Exit status 1`
`npm ERR!`
`npm ERR! Failed at the isolated-vm@3.3.3 install script.`
`npm ERR! This is probably not a problem with npm. There is likely additional logging output above.`

`npm ERR! A complete log of this run can be found in:`
`npm ERR!     /home/sergiu/.npm/_logs/2020-07-07T15_58_19_338Z-debug.log`

### What is the expected behavior?
isolated-vm to install fine, with node-gyp compiling with no errors.

**Comment by bnoordhuis** [comment]
You should report that against isolated-vm. That static_assert is a sanity check against misuse. It means isolated-vm is trying to do something that isn't supported.

**Comment by laverdet** [comment]
Thanks for raising this. It's a simple fix laverdet/isolated-vm@d00e8ac, I'll push it out to npm soonish.

**Comment by scimarin** [comment]
solved with the release of v3.3.4 of isolated-vm.
